# .streamlit/secrets.toml
# Este arquivo NÃO deve ser commitado no GitHub
# Configure no Streamlit Cloud ou mantenha apenas localmente

# Chave de criptografia dos dados
[encryption]
key = "SUA_CHAVE_DE_CRIPTOGRAFIA_AQUI"

# Dados criptografados (gerados pelo script encrypt_data.py)
[data]
encrypted_file = """
SEUS_DADOS_CRIPTOGRAFADOS_AQUI_EM_BASE64
"""

# Usuários e senhas (gerados pelo script generate_password.py)
[users]

[users.admin]
password_hash = "HASH_DA_SENHA_DO_ADMIN"
salt = "SALT_DO_ADMIN"

[users.usuario1]
password_hash = "HASH_DA_SENHA_DO_USUARIO1"
salt = "SALT_DO_USUARIO1"

# Adicione mais usuários conforme necessário